FROM gradle:9.5-jdk21 AS build
WORKDIR /home/app
COPY . /home/app
RUN gradle build --no-daemon

FROM openjdk:21-jdk-slim
EXPOSE 8080
COPY --from=build /home/app/build/libs/*.jar app.jar
ENTRYPOINT ["sh", "-c", "java -jar /app.jar"]